name: hlin
version: 0.1.0.0
github: 'molarmanful/hlin'
license: MIT
author: 'Benjamin Pang'
maintainer: 'ben.10@nyu.edu'
copyright: '2023 Benjamin Pang'

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/molarmanful/hlin#readme>

dependencies:
  - base >= 4.7 && < 5
  - flow == 2.0.*

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hlin:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlin

tests:
  hlin-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlin
